### ISSUE TITLE
当前语法无法正确识别 Block

### ISSUE THREAD

**Issue by fky2015** [jiweixing/30-day-compiler#36]
```scala
Number a = 0
Number b = 0
{
    Number b = 1
    {
        Number a = 2
    }
    {
        Number b = 3
    }
    a = a + 1
    b = b + 1
}
a = a + 1
b = b + 1
```
只能识别 L1-L2:
![image](https://user-images.githubusercontent.com/16451516/81296248-310a0d00-90a4-11ea-8312-88bebd54450f.png)

**Comment by sinofp** [comment]
不在for/if等语句内的block是被禁止的，CLParser里statement里没有空的block，加上应该就行了。
不过这种写法有需求么？

**Comment by fky2015** [comment]
这样的写法的唯一作用是希望提供自己定义作用域的可能。我也在考虑要不要把 AST 中的 Block 和这种括号完全映射上。

**Comment by sinofp** [comment]
我建议取消这种写法，因为没有必要。

现在ast里的block不是已经对应program、lambda、procedure definition、for/while、if-else了么，貌似所有大括号都被已经被当成block处理了吧（除了program没有大括号）。

**Comment by fky2015** [comment]
OK

**Comment by fky2015** [comment]
> 现在ast里的block不是已经对应program、lambda、procedure definition、for/while、if-else了么，貌似所有大括号都被已经被当成block处理了吧（除了program没有大括号）。

Program 里面倒是不应该用 Block

**Comment by sinofp** [comment]
> 
> 
> > 现在ast里的block不是已经对应program、lambda、procedure definition、for/while、if-else了么，貌似所有大括号都被已经被当成block处理了吧（除了program没有大括号）。
> 
> Program 里面倒是不应该用 Block

（我也觉得）
