### ISSUE TITLE
使用非平面的数据结构表示 类型

### ISSUE THREAD

**Issue by sinofp** [jiweixing/30-day-compiler#8]
现在 类型 在ast里是字符串，符号表里是枚举。但这样表示List<String>、List<List<String>>这样的 复合类型 就很牵强

**Comment by fky2015** [comment]
@sinofp 那我理解我需要在 AST 中也加入 typeNode 节点，然后采用跟你类似的方法来处理类型？

**Comment by sinofp** [comment]
@fky2015 我觉得类型检查时给AST的evalType赋值就行了吧，为啥要单独处理类型？

**Comment by fky2015** [comment]
那就没我啥事了？如果有，咱俩说的应该是一件事。

**Comment by sinofp** [comment]
其实HashMap<K, V>这种包含两种类型的复合类型还没完成。
